---
- name: make a build dir
  file: state=directory name=/root/yarn-nodemanager-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/yarn-nodemanager-dockerized/Dockerfile

- name: put run
  template: src=run dest=/root/yarn-nodemanager-dockerized/run mode=0755

- name: build a Docker image for YARN nodemanager
  command: docker build -t gitinsky/yarn-nodemanager:0.1.0 --rm /root/yarn-nodemanager-dockerized

- name: tag it as latest
  command: docker build -t gitinsky/yarn-nodemanager:latest --rm /root/yarn-nodemanager-dockerized
